str1 =c("the","ame","yagnesh","the","yagnesh")
print(str1)
print("Unique elements of the said vector:")
print(unique(tolower(str1)))
nums = c(1, 2, 2, 3, 4, 4, 5, 6)
print(nums)
print("Unique elements of the said vector:")
print(unique(nums))